baseurl = "/"
relativeurls = true
languageCode = "en-us"
title = "Urbana-Champaign UseR Group"
theme = "hugo-material"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$","\\.Rmarkdown$", "_files$", "_cache$"]
# publishDir = "public"

[permalinks]
    post = "/:year/:month/:day/:slug/"

[[menu.main]]
    identifier = "home"
    pre = "<i class='material-icons'>home</i>"
    name = "Home"
    url = "/"
    weight = 1
[[menu.main]]
    identifier = "about"
    name = "About"
    pre = "<i class='material-icons'>people</i>"
    url = "/about"
    weight = 2
[[menu.main]]
    identifier = "resources"
    name = "Resources"
    pre = "<i class='fa fa-2x fa-book-reader'></i>"
    url = "/resources"
    weight = 3
[[menu.main]]
    identifier = "getting-started-with-r"
    name = "Getting Started"
    pre = "<i class='fa fa-2x fa-hourglass-start'></i>"
    url = "/getting-started-with-r"
    weight = 1
    parent = "resources"
[[menu.main]]
    identifier = "r-at-uiuc"
    name = "R at UIUC"
    pre = "<i class='fa fa-2x fa-power-off'></i>"
    url = "/r-at-uiuc"
    weight = 2
    parent = "resources"
[[menu.main]]
    name = "RStudio Cloud"
    pre = "<i class='fa fa-2x fa-cloud'></i>"
    url = "https://rstudio.cloud/spaces/40189/join?access_code=p0zXu2obd7Ktu7wAviavJR1FmlMJn6djllSOEqnp"
    weight = 4
[[menu.main]]
    name = "Slack"
    pre = "<i class='fa fa-2x fab fa-slack'></i>"
    url = "https://go.illinois.edu/uc-ur-slack"
    weight = 5
[[menu.main]]
    name = "Email List"
    pre = "<i class='fa fa-2x fa-envelope-square'></i>"
    url = "https://groups.google.com/forum/#!forum/uc-ur/join"
    weight = 6

[[menu.footer]]
  weight = 1
  identifier = "Illinois"
  name = "UIllinois"
  pre = "<i class=\"material-icons\">pin_drop</i>"
  url = "https://illinois.edu"
[[menu.footer]]
  weight = 2
  identifier = "github"
  name = "GitHub"
  pre = "<i class=\"button-icon fa fa-2x fa-github\"></i>"
  url = "https://github.com/UrbanaChampaignUseR"
[[menu.footer]]
  weight = 3
  identifier = "coc"
  name = "Code of Conduct"
  pre = "<i class=\"button-icon fa fa-2x fa-balance-scale\"></i>"
  url = "https://wiki.r-consortium.org/view/R_Consortium_and_the_R_Community_Code_of_Conduct"
# [[menu.footer]]
#   weight = 3
#   identifier = "twitter"
#   name = "Twitter"
#   pre = "<i class=\"button-icon fa fa-2x fa-twitter\"></i>"
#   url = "https://twitter.com/cboettig"


[params]

    custom_css = ["example.css"]
#    custom_js = ["example.js"]

    date_format = "Mon, Jan 2, 2006"
    description = "A website built through Hugo and blogdown."

    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.15.8"
    highlightCDN = "//cdnjs.cloudflare.com"
    highlightjsLang = ["r"]
    highlightjsTheme = "tomorrow-night"

    [params.logo]
    url = "logo.png"
    width = 50
    height = 50
    alt = "Logo"

